apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
 - namespace-llama-stack.yaml
 - secret-pgvector.yaml 

helmCharts:
  - name: pgvector
    repo: ./charts
    releaseName: pgvector
    namespace: llama-stack