apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
 - namespace-llama-stack.yaml
 - secret-pgvector.yaml 

helmGlobals:
  chartHome: ../charts

helmCharts:
  - name: pgvector
    version: 0.1.0
    releaseName: pgvector
    namespace: llama-stack