kind: Secret
apiVersion: v1
metadata:
  name: llama-stack-secret
  labels:
    app.kubernetes.io/instance: llama-stack-secret
data:
  # Base64 encoded tokens - replace with your actual tokens
  deepseek-token: c2stRmZ4QjFOdmpTNjlfQnktZ2hNT1g5dw==
  granite-token: c2stRmZ4QjFOdmpTNjlfQnktZ2hNT1g5dw==
  llama-token: c2stRmZ4QjFOdmpTNjlfQnktZ2hNT1g5dw==
  llama17b-token: c2stRmZ4QjFOdmpTNjlfQnktZ2hNT1g5dw==
  slack-bot-token: c2stRmZ4QjFOdmpTNjlfQnktZ2hNT1g5dw==
  slack-team-id: c2stRmZ4QjFOdmpTNjlfQnktZ2hNT1g5dw==
type: Opaque
