apiVersion: v1
kind: Secret
metadata:
  name: pgvector
  namespace: llama-stack
type: Opaque
stringData:
  pgvector-host: pgvector.llama-stack.svc.cluster.local
  pgvector-port: "5432"
  pgvector-db: pgvector
  pgvector-registry-db: pgvector-registry
  pgvector-user: pguser
  pgvector-password: opensesame
