apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - ./model-registry
  - ./mysql-db

patches:
  - path: patch-datasciencecluster.yaml
    target:
      kind: DataScienceCluster
