apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-operators
spec:
  generators:
  - list:
      elements:
      - cluster: local
        url: https://kubernetes.default.svc
        values:
          name: leader-worker-set-operator
          path: components/operators/leader-worker-set/aggregate/overlays/default
      - cluster: local
        url: https://kubernetes.default.svc
        values:
          name: nvidia-gpu-operator
          path: components/operators/gpu-operator-certified/aggregate/overlays/aws
      - cluster: local
        url: https://kubernetes.default.svc
        values:
          name: nfd-operator
          path: components/operators/nfd/aggregate/overlays/default
      - cluster: local
        url: https://kubernetes.default.svc
        values:
          name: openshift-custom-metrics-autoscaler-operator
          path: components/operators/openshift-custom-metrics-autoscaler/operator/overlays/stable
      - cluster: local
        url: https://kubernetes.default.svc
        values:
          name: openshift-ai-operator
          path: components/operators/openshift-ai/aggregate/overlays/fast-nvidia-gpu
      - cluster: local
        url: https://kubernetes.default.svc
        values:
          name: openshift-gitops-operator
          path: components/operators/openshift-gitops/aggregate/overlays/rhdp
      - cluster: local
        url: https://kubernetes.default.svc
        values:
          name: openshift-pipelines-operator
          path: components/operators/openshift-pipelines/operator/overlays/latest
      - cluster: local
        url: https://kubernetes.default.svc
        values:
          name: redhat-build-of-kueue-operator
          path: components/operators/redhat-build-of-kueue/aggregate/overlays/stable-v1.1
      - cluster: local
        url: https://kubernetes.default.svc
        values:
          name: openshift-serverless-operator
          path: components/operators/openshift-serverless/aggregate/overlays/rhdp
      - cluster: local
        url: https://kubernetes.default.svc
        values:
          name: streams-for-apache-kafka-operator
          path: components/operators/streams-for-apache-kafka/operator/overlays/stable
      # 
      # First list on main README: 
        # OpenShift AI + [Installed]
        # Serverless Operator +  [Installed]
        # Streams for Apache Kafka Operator + [Installed]
        # Knative Eventing + [Installed]
        # Knative Kafka w/ broker functionality enabled [Installed]

      # Sukantas list:
      #       Setting up observability infrastructure: needs few operator
      # cluster-observability-operator - PodMonitor/ServiceMonitor CRDs and UI plugins
      # grafana-operator - Grafana operator for visualization and dashboard management
      # otel-operator - Red Hat Build of OpenTelemetry operator
      # tempo-operator - Distributed tracing backend operator


      # - cluster: local
      #   url: https://kubernetes.default.svc
      #   values:
      #     name: openshift-logging-operator
      #     path: components/operators/openshift-logging/aggregate/overlays/default
      # - cluster: local
      #   url: https://kubernetes.default.svc
      #   values:
      #     name: web-terminal-operator
      #     path: components/operators/web-terminal-operator/operator/overlays/fast
