apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace: rhoai-model-registry-mysql-db

resources:
  - model-registry-db-parameters.yaml
  - mysql-deployment.yaml
  - mysql-ns.yaml
  - mysql-pvc.yaml
  - mysql-secret.yaml
  - mysql-service.yaml
  - rolebinding.yaml
