kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: metadata-mysql-rhoai-model-registry
  namespace: rhoai-model-registry-mysql-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
